version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - servicos-network
  web:
    links:
      - 'database:mysql'
    build: .
    command: npm start
    volumes:
      - .:/usr/app
    ports:
      - "3333:3333"
    depends_on:
      - database
    networks:
      - servicos-network
networks:
  servicos-network:
    driver: bridge