version: '3'
services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "infoq"
    ports:
      - "3306:3306"
    volumes:
      - /Users/tiago/data/mysql:/var/lib/mysql